name: jkvttplugin
version: '1.0-SNAPSHOT'
main: io.papermc.jkvttplugin.JkVttPlugin
api-version: '1.21'
commands:
  spawnhadozee:
    description: Spawn a Hadozee NPC
    usage: /spawnhadozee
  rolldice:
    description: Roll dice using XdY format (e.g., 2d6+3).
    usage: /rolldice <XdY[+Z]>
    permission: dnd.rolldice
  reloadyaml:
    description: Reloads all YAML files (Weapons & NPCs).
    usage: /reloadyaml
    permission: jkvttplugin.reloadyaml
    permission-message: You do not have permission to use this command.
  createcharacter:
    description: Start character creation.
    usage: /createcharacter
#    permission: jkvttplugin.createcharacter
  closesheet:
    description: Save and close the active character sheet.
    usage: /closesheet
    permission: jkvttplugin.closesheet
    permission-message: You do not have permission to use this command.
  shortrest:
    description: Take a short rest (1 hour) to recover resources.
    usage: /shortrest
    permission: jkvttplugin.shortrest
    permission-message: You do not have permission to take a short rest.
  longrest:
    description: Take a long rest (8 hours) to recover HP and resources.
    usage: /longrest
    permission: jkvttplugin.longrest
    permission-message: You do not have permission to take a long rest.
  rest:
    description: (DM) Trigger a rest for a character.
    usage: /rest <character> <short|long>
    permission: jkvttplugin.rest
    permission-message: You do not have permission to use this command.
  restoreresource:
    description: (DM) Restore a character's class resource.
    usage: /restoreresource <character> <resourceName|all>
    permission: jkvttplugin.restoreresource
    permission-message: You do not have permission to use this command.
  consumeresource:
    description: (DM) Consume a character's class resource.
    usage: /consumeresource <character> <resourceName> [amount]
    permission: jkvttplugin.consumeresource
    permission-message: You do not have permission to use this command.
  dmentity:
    description: (DM) Spawn and manage entities in the world.
    usage: /dmentity <spawn|list|remove|teleport|spawngroup>
    permission: jkvtt.dm
    permission-message: You do not have permission to use this command.
  dmgive:
    description: (DM) Give D&D items to players.
    usage: /dmgive <player> <item_id> [amount]
    permission: jkvtt.dm
    permission-message: You do not have permission to use this command.
  dm:
    description: Manage DM (Dungeon Master) role assignments.
    usage: /dm <add|remove|list>
    permission-message: Only server operators can manage DMs.
