name: jkvttplugin
version: '1.0-SNAPSHOT'
main: io.papermc.jkvttplugin.JkVttPlugin
api-version: '1.21'
commands:
  spawnhadozee:
    description: Spawn a Hadozee NPC
    usage: /spawnhadozee
  rolldice:
    description: Roll dice using XdY format (e.g., 2d6+3).
    usage: /rolldice <XdY[+Z]>
    permission: dnd.rolldice
  reloadyaml:
    description: Reloads all YAML files (Weapons & NPCs).
    usage: /reloadyaml
    permission: jkvttplugin.reloadyaml
    permission-message: You do not have permission to use this command.
  createcharacter:
    description: Start character creation.
    usage: /createcharacter
#    permission: jkvttplugin.createcharacter
