package io.papermc.jkvttplugin.ui.action;

public enum MenuAction {
    OPEN_RACE_SELECTION,
    CHOOSE_RACE,
    CHOOSE_SUBRACE,
    CHOOSE_CLASS,
    CHOOSE_BACKGROUND,
    CHOOSE_OPTION,
    DRILLDOWN_OPEN,
    DRILLDOWN_PICK,
    DRILLDOWN_BACK,
    CONFIRM_PLAYER_CHOICES,
    INCREASE_ABILITY,
    DECREASE_ABILITY,
    CONFIRM_CHARACTER,
}
