package io.papermc.jkvttplugin.ui.core;

public enum MenuType {
    VIEW_CHARACTER_SHEET,
    CHARACTER_CREATION_SHEET,
    RACE_SELECTION,
    SUBRACE_SELECTION,
    CLASS_SELECTION,
    BACKGROUND_SELECTION,
    PLAYERS_CHOICES,
    ABILITY_ALLOCATION,
    SPELL_SELECTION
}
